id = "qter"
name = "Qter Language"
version = "0.1.0"
schema_version = 1
authors = ["Arhan Chaudhary <arhan.ch@gmail.com>"]
description = "Q (and soon QAT) language support for Qter"
repository = "https://github.com/qter-project/zed-extension-qter"

[grammars.qter_q]
repository = "https://github.com/qter-project/tree-sitter-q"
rev = "af56bc6adef54bf16f7074f5f93ea871b24f9fd4"
